version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
  bot:
    build: .
    container_name: "currency_bot"
    env_file:
      - .env
    depends_on:
      - redis
